[package]
name = "cargo-spellcheck"
version = "0.2.5-alpha.0"
authors = ["Bernhard Schuster <bernhard@ahoi.io>"]
edition = "2018"
repository = "https://github.com/drahnr/cargo-spellcheck.git"
homepage = "https://github.com/drahnr/cargo-spellcheck"
license = "MIT OR Apache-2.0"
keywords = ["spellcheck", "spelling", "grammar"]
description = "Checks all doc comments for spelling mistakes"
readme = "README.md"

[dependencies]
docopt = "1"
serde = { version = "1", features = ["derive"] }
anyhow = "1"
proc-macro2 = { version = "1", features = ["span-locations"] }
walkdir = "2"
syn = { version = "1", features = ["full"] }
log = "0.4"
env_logger = "0.7"
console = "0.11"
indexmap = "1"
enumflags2 = "0.6"
# for the config file
toml = "0.5"
# for parsing and extracting elements from Cargo.toml
cargo_toml = "0.8"
directories = "2"
lazy_static = "1"
pulldown-cmark = "0.7"
itertools = "0.9"
crossterm = "0.17"
regex = "1"
signal-hook = "0.1"
termios = "0.3"

# config parsing, must be independent of features
iso_country = { version = "0.1" }
isolang = { version = "1", features = ["serde_serialize"] }
url = { version = "2", features = ["serde"] }

# dictionary
hunspell-rs = { version = "0.1", optional = true }

# full grammar check
languagetool-rs = { version = "0.1", package = "languagetool", optional = true }

[features]
default = ["hunspell"]

languagetool = ["languagetool-rs"]
hunspell = ["hunspell-rs"]

all = ["hunspell", "languagetool"]
